# Generated by Django 5.2.3 on 2025-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='componentName',
            field=models.CharField(choices=[('Height', 'Height'), ('Weight', 'Weight'), ('Blood Pressure', 'Blood Pressure'), ('HeartRate', 'Heart Rate')], max_length=20),
        ),
    ]
