upstream django_cluster {
    server app1:8000;
    server app3:8000;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;
    
    location / {
        proxy_pass http://django_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}

server {

    listen 8080;
    server_name localhost;

    location / {
        return 301 https://$host$request_uri;
    }
}