version: "3.9"

services:

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: clinical_db
      MYSQL_USER: super_admin
      MYSQL_PASSWORD: Django_0359
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: >
      sh -c "
      echo 'Waiting for DB...';
      while ! nc -z db 3306; do sleep 1; done;
      echo 'DB is up!';
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy

  app1:
    build: .
    command: >
      sh -c "
      echo 'Waiting for DB...';
      while ! nc -z db 3306; do sleep 1; done;
      echo 'DB is up!';
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - APP_NAME=App1
    depends_on:
      db:
        condition: service_healthy

  app3:
    build: .
    command: >
      sh -c "
      echo 'Waiting for DB...';
      while ! nc -z db 3306; do sleep 1; done;
      echo 'DB is up!';
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - APP_NAME=App3
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - D:/nginx-certs:/etc/nginx/certs
    depends_on:
      - web
      - app1
      - app3

volumes:
  mysql_data: